[project]
name = "demo-in-memory-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawlee[cli,parsel]>=0.6.9",
]
